version: '3.8'

services:
  # 節點 1 (Leader)
  ledger-node1:
    build: .
    container_name: jraft-ledger-node1
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=cluster
      - RAFT_NODE_ID=ledger-node1:8081
      - RAFT_NODE_PORT=8081
      - RAFT_GROUP_ID=ledger_cluster
      - RAFT_DATA_PATH=/app/raft_data
      - RAFT_CLUSTER_CONFIG=ledger-node1:8081,ledger-node2:8081,ledger-node3:8081
      - SERVER_PORT=8080
    volumes:
      - node1_data:/app/raft_data
    networks:
      - ledger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ledger/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 節點 2
  ledger-node2:
    build: .
    container_name: jraft-ledger-node2
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=cluster
      - RAFT_NODE_ID=ledger-node2:8081
      - RAFT_NODE_PORT=8081
      - RAFT_GROUP_ID=ledger_cluster
      - RAFT_DATA_PATH=/app/raft_data
      - RAFT_CLUSTER_CONFIG=ledger-node1:8081,ledger-node2:8081,ledger-node3:8081
      - SERVER_PORT=8080
    volumes:
      - node2_data:/app/raft_data
    networks:
      - ledger-network
    depends_on:
      - ledger-node1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ledger/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 節點 3
  ledger-node3:
    build: .
    container_name: jraft-ledger-node3
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=cluster
      - RAFT_NODE_ID=ledger-node3:8081
      - RAFT_NODE_PORT=8081
      - RAFT_GROUP_ID=ledger_cluster
      - RAFT_DATA_PATH=/app/raft_data
      - RAFT_CLUSTER_CONFIG=ledger-node1:8081,ledger-node2:8081,ledger-node3:8081
      - SERVER_PORT=8080
    volumes:
      - node3_data:/app/raft_data
    networks:
      - ledger-network
    depends_on:
      - ledger-node1
      - ledger-node2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/ledger/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 監控和管理界面 (可選)
  nginx-proxy:
    image: nginx:alpine
    container_name: jraft-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ledger-network
    depends_on:
      - ledger-node1
      - ledger-node2
      - ledger-node3

volumes:
  node1_data:
  node2_data:
  node3_data:

networks:
  ledger-network:
    driver: bridge 