global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ledger-nodes'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'ledger-node-1:8080'
          - 'ledger-node-2:8080'
          - 'ledger-node-3:8080'
        labels:
          app: 'ledger'
          component: 'state-machine'

  - job_name: 'projection'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ledger-projection:8089']
        labels:
          app: 'ledger'
          component: 'projection'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
