server:
  port: 8080

spring:
  application:
    name: jraft-ledger-system
  
  datasource:
    url: jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

# JRaft 配置
raft:
  node:
    id: 127.0.0.1:8081
    port: 8081
  group:
    id: ledger_group
  data:
    path: ./raft_data
  cluster:
    config: 127.0.0.1:8081

# 日誌配置
logging:
  level:
    com.example.ledger: DEBUG
    com.alipay.sofa.jraft: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 